version: '3.5'
services:
  db:
    container_name: db
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


# how to access the database client:
# docker exec -it db psql -U postgres