version: '3.5'
services:
  db_back:
    container_name: db
    image: postgres
    ports: 
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  pgdata:
    external: false
